server:  port: 8180
spring:
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:file:./db/productos
        username: Admin
        password: 123456